In [1]:
from tensorflow import keras
import pandas as pd
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split

import seaborn as sns
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf

In [2]:
data = datasets.load_iris()

In [3]:
type(data)

sklearn.utils._bunch.Bunch

In [4]:
df = pd.DataFrame(data.data, columns = data.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df["species"] = data.target

In [24]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [25]:
df.shape

(150, 5)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [27]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)     species  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [28]:
np.unique(df["species"], return_counts = True)

(array([0, 1, 2]), array([50, 50, 50], dtype=int64))

In [29]:
# 데이터 분할
x = df.drop("species", axis = 1)
y = df["species"]

In [30]:
# 종속변수 값 확인
y.value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [31]:
x.shape

(150, 4)

In [32]:
# input_shape() 값에 넣는 개수
x.iloc[0] 

sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

In [35]:
# 모델 구성
model = keras.Sequential()
model.add(keras.layers.Dense(16, activation = "relu", input_shape = (4,)))
model.add(keras.layers.Dense(3, activation = "softmax"))

- 16, activation = "relu" 여기 부분(은닉층)은 자유롭게 쓸 수 있음
- 출력층은 아님
    - 3, activation = "softmax" 이 부분은 고정

In [36]:
y.shape

(150,)

In [37]:
model.compile(loss = "sparse_categorical_crossentropy", optimizer = "adam",
             metrics = ["accuracy"])

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify = y, test_size = 0.2,
                                                   random_state = 12)

In [39]:
x_sub, x_val, y_sub, y_val = train_test_split(x_train, y_train, stratify = y_train,
                                             test_size = 0.2, random_state = 12)

In [41]:
x_sub.shape

(96, 4)

In [42]:
model.fit(x_sub, y_sub, epochs = 50, validation_data = (x_val, y_val), batch_size = 4)

Epoch 1/50
24/24 [==============================] - 0s 4ms/step - loss: 0.6228 - accuracy: 0.6562 - val_loss: 0.6167 - val_accuracy: 0.7083
Epoch 2/50
24/24 [==============================] - 0s 3ms/step - loss: 0.5985 - accuracy: 0.7188 - val_loss: 0.5923 - val_accuracy: 0.6667
Epoch 3/50
24/24 [==============================] - 0s 3ms/step - loss: 0.5775 - accuracy: 0.6771 - val_loss: 0.5718 - val_accuracy: 0.7500
Epoch 4/50
24/24 [==============================] - 0s 3ms/step - loss: 0.5483 - accuracy: 0.7917 - val_loss: 0.5531 - val_accuracy: 0.7500
Epoch 5/50
24/24 [==============================] - 0s 3ms/step - loss: 0.5283 - accuracy: 0.7188 - val_loss: 0.5394 - val_accuracy: 0.7500
Epoch 6/50
24/24 [==============================] - 0s 3ms/step - loss: 0.5117 - accuracy: 0.8229 - val_loss: 0.5233 - val_accuracy: 0.7917
Epoch 7/50
24/24 [==============================] - 0s 2ms/step - loss: 0.5038 - accuracy: 0.8229 - val_loss: 0.5112 - val_accuracy: 0.7917
Epoch 8/50
24/24 [==

- to_categorical()

In [43]:
encoded_y = keras.utils.to_categorical(y)

In [44]:
encoded_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x, encoded_y, stratify = encoded_y, test_size = 0.2,
                                                   random_state = 12)

In [46]:
x_sub, x_val, y_sub, y_val = train_test_split(x_train, y_train, stratify = y_train,
                                             test_size = 0.2, random_state = 12)

In [47]:
y_val[:5]

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [48]:
model2 = keras.Sequential()
model2.add(keras.layers.Dense(16, activation = "relu", input_shape = (4,)))
model2.add(keras.layers.Dense(3, activation = "softmax"))

In [49]:
model2.compile(loss = "categorical_crossentropy",
              optimizer = "adam", metrics = "accuracy")

In [50]:
model2.fit(x_sub, y_sub, epochs = 100, batch_size = 8, validation_data = (x_val, y_val))

Epoch 1/100
12/12 [==============================] - 1s 15ms/step - loss: 1.4255 - accuracy: 0.1042 - val_loss: 1.3539 - val_accuracy: 0.1250
Epoch 2/100
12/12 [==============================] - 0s 4ms/step - loss: 1.2995 - accuracy: 0.0833 - val_loss: 1.2411 - val_accuracy: 0.2083
Epoch 3/100
12/12 [==============================] - 0s 3ms/step - loss: 1.1915 - accuracy: 0.0833 - val_loss: 1.1352 - val_accuracy: 0.1250
Epoch 4/100
12/12 [==============================] - 0s 5ms/step - loss: 1.0973 - accuracy: 0.1146 - val_loss: 1.0552 - val_accuracy: 0.2083
Epoch 5/100
12/12 [==============================] - 0s 4ms/step - loss: 1.0220 - accuracy: 0.1250 - val_loss: 0.9967 - val_accuracy: 0.1250
Epoch 6/100
12/12 [==============================] - 0s 3ms/step - loss: 0.9687 - accuracy: 0.1875 - val_loss: 0.9504 - val_accuracy: 0.2083
Epoch 7/100
12/12 [==============================] - 0s 4ms/step - loss: 0.9216 - accuracy: 0.2083 - val_loss: 0.9132 - val_accuracy: 0.3333
Epoch 8/100


Epoch 59/100
12/12 [==============================] - 0s 4ms/step - loss: 0.3972 - accuracy: 0.9583 - val_loss: 0.4014 - val_accuracy: 0.9583
Epoch 60/100
12/12 [==============================] - 0s 3ms/step - loss: 0.3937 - accuracy: 0.9271 - val_loss: 0.4005 - val_accuracy: 0.9167
Epoch 61/100
12/12 [==============================] - 0s 4ms/step - loss: 0.3913 - accuracy: 0.9271 - val_loss: 0.3947 - val_accuracy: 0.9167
Epoch 62/100
12/12 [==============================] - 0s 4ms/step - loss: 0.3864 - accuracy: 0.9479 - val_loss: 0.3905 - val_accuracy: 0.9167
Epoch 63/100
12/12 [==============================] - 0s 4ms/step - loss: 0.3856 - accuracy: 0.9479 - val_loss: 0.3856 - val_accuracy: 0.9583
Epoch 64/100
12/12 [==============================] - 0s 3ms/step - loss: 0.3848 - accuracy: 0.9479 - val_loss: 0.3859 - val_accuracy: 0.9167
Epoch 65/100
12/12 [==============================] - 0s 3ms/step - loss: 0.3754 - accuracy: 0.9479 - val_loss: 0.3802 - val_accuracy: 0.9167
Epoch 